[project]
name = "ytdlbot"
version = "0.1.0"
description = "Telegram Video Downloader Bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.1",
    "python-telegram-bot>=21.7",
    "validators>=0.34.0",
    "yt-dlp>=2024.11.4",
]
